//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public abstract class Deck : IDeck
	{
		private string deckName;
		private Dictionary<int, ICard> cardsInDeck = new Dictionary<int, ICard>();

		public int getTotalCardsOfDeck()
		{
			return this.cardsInDeck.Count;
		}
		
		//Deck modification
		public void removeCardFromDeck(int cardID) 
		{
			this.cardsInDeck.Remove (cardID);
		}

		public void addCardToDeck(ICard card)
		{
			this.cardsInDeck.Add (card.getCardID (), card);
		}
		
		//Deck actions
		public ICard drawCardFromDeck(int cardID)
		{
			return this.cardsInDeck [cardID];
		}

	}
}

