//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class CharacterCard : Card
	{
		private string name;
		private int hp;
		private int st;
		private int sp;
		private int ac;
		private int lk;

		public void setName(string name)
		{
			this.name = name;
		}
		
		public void setHP(int hp)
		{
			this.hp = hp;
		}
		
		public void setST(int st)
		{
			this.st = st;
		}
		
		public void setSP(int sp)
		{
			this.sp = sp;
		}
		
		public void setAC(int ac)
		{
			this.ac = ac;
		}
		
		public void setLK(int lk)
		{
			this.lk = lk;
		}
		
		public string getName()
		{
			return this.name;
		}
		
		public int getHP()
		{
			return this.hp;
		}
		
		public int getST()
		{
			return this.st;
		}
		
		public int getSP()
		{
			return this.sp;
		}
		
		public int getAC()
		{
			return this.ac;
		}
		
		public int getLK()
		{
			return this.lk;
		}
	}
}

