//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Player : IPlayer
	{
		private int playerID;
		private CharacterCard characterChosen;

		public int getPlayerID()
		{
			return this.playerID;
		}

		public void setPlayerID(int playerID)
		{
			this.playerID = playerID;
		}

		public void setPlayerCharacterCard(CharacterCard playerCard)
		{
			this.characterChosen = playerCard;
		}

		public CharacterCard getPlayerCharacterCard()
		{
			return this.characterChosen;
		}
	}
}

