//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class PlayerDeck
	{
		private string deckName;
		private Dictionary<int, Player> playersInGame = new Dictionary<int, Player>();
		
		public int getTotalPlayers()
		{
			return this.playersInGame.Count;
		}
		
		//Deck modification
		public void removePlayerFromGame(int playerID) 
		{
			this.playersInGame.Remove (playerID);
		}
		
		public void addPlayerToRoster(Player player)
		{
			this.playersInGame.Add (player.getPlayerID(), player);
		}

		public Player getPlayerFromRoster(int playerID)
		{
			return this.playersInGame [playerID];
		}
	}
}

