//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public static class DiceRoll
	{
		public static System.Random diceRoller = new System.Random();
		private static  int FirstDiceResult = 0;
		private static int SecondDiceResult = 0;

		public static int rollOneDice()
		{
			return diceRoller.Next (1, 7);
		}

		public static int rollTwoDice()
		{
			return diceRoller.Next (1, 12);
		}

		public static void logResult()
		{
			Debug.Log (rollOneDice ());
		}

		public static void setFirstDiceResult(int diceResult)
		{
			FirstDiceResult = diceResult;
		}

		public static void setSecondDiceResult(int diceResult) 
		{
			SecondDiceResult = diceResult;
		}

		public static int GetFirstDiceResult()
		{
			return FirstDiceResult;
		}

		public static int GetSecondDiceResult()
		{
			return SecondDiceResult;
		}

	}
}

