//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public interface IDeck
	{	
		//Statistics
		int getTotalCardsOfDeck();

		//Deck modification
		void removeCardFromDeck(int cardID);
		void addCardToDeck(ICard card);

		//Deck actions
		ICard drawCardFromDeck(int cardID);
	}
}

