//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public static class ChoosingPlayerController
	{/*
		public static int currentPlayerID = 1;
		public static bool choosingOver = false;

		public static bool PlayerChoseThisCard(int cardID)
		{
			PlayerRoster.getPlayerFromRoster (currentPlayerID).setPlayerCharacterCard (CharacterDeck.drawCharacterCardFromDeck (cardID));
			//Debug.Log ("Player " + currentTurn +fdsf " has chosen " + CharacterDeck.drawCharacterCardFromDeck(cardID).getName() + ".");
			CharacterDeck.removeCharacterFromDeck (cardID);
			currentPlayerID++;
			if (currentPlayerID == 5) 
			{
				choosingOver = true;
			}

			return choosingOver;

		}
	*/}
}

