//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class CreateObjectClass : MonoBehaviour 
	{
		/*
		public void createCharacterRoster()
		{
			//Debug.Log (CharacterDeck.getTotalCards());
			for (int i = 1; i <= CharacterDeck.getTotalCards(); i++) 
			{
				//Debug.Log (i);
				createCharacterCardObject(CharacterDeck.drawCharacterCardFromDeck(i));
			}
		}

		public void createCharacterCardObject(CharacterCard character)
		{
			FR_MANAGER.generateCharacterLineUpCard (character.getPrefabName (), character.getCardID (), CharacterDeck.getTotalCards());
		}*/
	}
}

