//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class PlayerController
	{
		public PlayerDeck playerDeck = new PlayerDeck();
		
		
		public void addPlayerToGame(Player player)
		{
			Player newPlayer = player;
			//Debug.Log ("Player: " + player.getPlayerID() + " has been added to the deck.");
			playerDeck.addPlayerToRoster (player);
		}
		
		public void removePlayerFromGame(int playerID)
		{
			playerDeck.removePlayerFromGame (playerID);
		}
		
		public Player getPlayerFromRoster(int playerID)
		{
			Player chosenPlayer = new Player ();
			chosenPlayer = playerDeck.getPlayerFromRoster (playerID);
			//Debug.Log ("Retrieved Player " + chosenPlayer.getPlayerID() + ".");
			return chosenPlayer;
		}
		
		public CharacterCard getPlayersChosenCard(int playerID)
		{
			return playerDeck.getPlayerFromRoster (playerID).getPlayerCharacterCard ();
		}
		
		public void setPlayerChosenCharacterCard(int playerID, CharacterCard characterCard)
		{
			getPlayerFromRoster (playerID).setPlayerCharacterCard (characterCard);
		}
		
		public int getTotalPlayers()
		{
			return playerDeck.getTotalPlayers ();
		}
	}
}

